### ISSUE TITLE
Provide support for Ueberauth

### ISSUE THREAD

**Issue by lucperkins** [aaronrenner/phx_gen_auth#20]
Sorry for the annoying feature request, but I do think that a lot of people would use `phx.gen.auth` with the hope of providing support for both standard username/password auth flows *and* external auth providers (Google, GitHub, Apple, etc.). At the moment, `ueberauth` appears to be a de facto standard, and adding an `--ueberauth` option to `phx.gen.auth` would be great. Would be happy to help but wanted to see what you think first.

**Comment by josevalim** [comment]
Our goal with mix phx.gen.auth is exactly for it to be a starting point, we really don't plan on adding more features to it. More info here:  https://dashbit.co/blog/a-new-authentication-solution-for-phoenix

My hope is that adding uberauth to it in the future will be super easy because we will start having more guides and documentation on those specific integrations. So if you want to help, I would say writing such guide would be a great starting point. :)

**Comment by niccolox** [comment]
its happening 
https://iacobson.medium.com/phx-gen-auth-and-oauth-for-a-phoenix-liveview-app-a19a27e6befa
