### ISSUE TITLE
"Confirm email" instead of "confirm user"

### ISSUE THREAD

**Issue by thojanssens** [aaronrenner/phx_gen_auth#26]
Reading the code, we "confirm a user" through email confirmation.
I'm not convinced about the naming; I find it too ambiguous.

Why not talk about "confirm an email". It is more explicit. What does "confirming a user" really means. Furthermore, we might want to to confirm a phone number by SMS some day as well.

Just semantics. (Just in case you agree, let me know if you need help to refactor, it's a lot of changes).

For example `confirm_user(token)` should be `confirm_email(token)`, `confirm_changeset` to `confirm_email_changeset`, etc.

**Comment by josevalim** [comment]
We need to keep the `user` prefix, in case of multiple generated auth resources in the same context and to follow Phoenix conventions. But I agree adding `email` can be helpful, so I propose `confirm_user_email` (and `confirm_user_email_multi`).

**Comment by josevalim** [comment]
`confirm_changeset` should stay as `confirm_changeset`, as it doesn't touch the e-mail, only the `confirmed_at` column.

**Comment by thojanssens** [comment]
But the `confirmed_at` falls into the same reasoning. What exactly is confirmed? We confirmed the existence of the user's email. It should be `confirmed_email_at`.

Reiterating what I said earlier, confirming an account doesn't make sense technically (as to me). We confirm the existence of the email that he registered with. We can also add `confirmed_mobile_number_at` some day.

**Comment by josevalim** [comment]
> What exactly is confirmed? We confirmed the existence of the user's email. It should be confirmed_email_at.

Today only e-mail can be confirmed, then there is no ambiguity.

For example, some applications may actually allow you to have multiple e-mails at the same time. In those cases, you have a confirmed_at column which is set once when the first e-mail confirmed and it gives the user confirmed access to the app plus one email+confirmed_at columns for each specific e-mail. In this case, you end-up with a confirmed_at column and the e-mail specific ones.

As I said in the other issue, we are really not interested in fail proofing the generator for what if scenarios, because there are way too many different ways we can go about it. :) Some of them would go at odds with confirmed_at, others won't.

**Comment by josevalim** [comment]
Another reason why we shouldn't change `confirmed_at` in the current code: if you change your e-mail, we don't update the `confirmed_at` to the date you entered the new e-mail. Maybe this should be even a reason to keep it as `confirm_user` but I will let @aaronrenner chime in. :)

EDIT: the more I think about this, the more I think the e-mail is only a mechanism for confirmation. If you have multiple entries (e-mail, sms), you may want to track each of them individually (confirm_email_at, confirm_sms_at) or not at all, but you will always to store the first time the user has ever confirmed their account, which is what this column tracks.

**Comment by thojanssens** [comment]
> I think the e-mail is only a mechanism for confirmation

> you will always to store the first time the user has ever confirmed their account, which is what this column tracks.

For me, the email confirmation is **only** to make sure to send emails to a valid address (otherwise it is bad for your sender reputation), and to make sure that this email belongs to the user (avoid sending emails to another person). Hence, it specifically confirms an email.

So if you say that `confirmed_at` date doesn't change when entering a new email. Now I question the whole existence of this field:-D

> but you will always to store the first time the user has ever confirmed their account, which is what this column tracks.

I will keep track of the date of registration, and maybe the date he confirmed a specific email or mobile number (little value, but sure instead of a boolean, why not a date for some more information). I don't see the point of keeping track of the date of the **first ever email** he registered with specifically.

If a developer wants to support multiple emails for a user, then up to the developer to change the design (he can add a new table or JSONB).

> As I said in the other issue, we are really not interested in fail proofing the generator for what if scenarios

Totally understand that; here the naming that I suggest is better IMO anyway, it express better its purpose, and it helps (me for example) to add more simply a `confirmed_mobile_number_at` as well.

I will stand by my point of view here that we confirm **an email** specifically.

**Comment by thojanssens** [comment]
I will add to that, that the confirmation of the account/user, is the user pressing on the "Register" button of the registration form :) He just *confirmed* he wants an account on your website.

Then an email is sent, allowing to make sure we have the valid user's email, in order to further safely send emails to that address.

If he changes his email address, that address again needs to be confirmed, in order to safely send emails.

**Comment by josevalim** [comment]
Registering is not the same as confirmation. E-mails in web apps are often used to confirm the identity of the user - which is why most apps do not allow the same e-mail to be used in more than one account. If it existed only for communication purposes, the uniqueness would be an artificial restriction.

For most apps, the e-mail is a good enough identity. For other apps, it isn't. Other apps don't require any mechanism for identity or they use an arbitrary one, such as username. Having an idea of when the user first confirmed their identity is valuable information. In such interpretation, the e-mail is more than a communication mechanism.

> If a developer wants to support multiple emails for a user, then up to the developer to change the design (he can add a new table or JSONB).

Exactly. If you want to add SMS or mobile number confirmation, then it is up to you to change the design too.

You are of course welcome to keep your interpretation. All I can do is to tell my understanding as the designer of the system. You are welcome to change it as you prefer.

**Comment by thojanssens** [comment]
Indeed if we think of "confirmed at" as "confirmed identity at", the naming makes more sense.

If you register with the email of someone else, and there is no confirming mechanism, you are preventing that someone else to create an account on your website. This is an issue and we're talking about identifiers in this interpretation.

Thank you, I'll close this issue :)

**Comment by thojanssens** [comment]
By the way

> Another reason why we shouldn't change confirmed_at in the current code: if you change your e-mail, we don't update the confirmed_at to the date you entered the new e-mail.

> but you will always to store the first time the user has ever confirmed their account, which is what this column tracks.

I just read in the code (last sentence in the doc below):

```
@doc """
Updates the user e-mail in token.

If the token matches, the user email is updated and the token is deleted.
The confirmed_at date is also updated to the current time.
"""
def update_user_email(user, token) do
```

So if we change the email, the `confirmed_at` does also change. So it is not the date of the first time ever he confirmed that the identity belongs to him (email).

**Comment by josevalim** [comment]
Yes, you are correct. I was probably considering an earlier design of the system. I will double check which date we would rather hold. Thanks.
