### ISSUE TITLE
Update terminology usage (e-mail vs email).

### ISSUE THREAD

**Issue by zorn** [aaronrenner/phx_gen_auth#49]
When applying this to my own projects I saw two terminology discrepancies.

I feel like `e-mail` should be `email`.

https://twitter.com/APStylebook/status/48798366980780033

I also lean toward `sign in` / `sign out` instead of `log in` / `log out`. 

One of the main reasons I do this is to avoid the confusion between a login name and the verb log in. In my observations most system have difficulty with consistency here. Some other observations / usability studies of the topic are collected here:

https://blog.benjamincharity.com/log-in-vs-login-vs-sign-in/

I know these can be well contested topics but if there was agreement I'd be happy to work on a PR. 

Even if the project sticks with the current stuff, I think it might be a helpful addition to make a patterns guide explaining why certain decisions were made, for usability reasons or security reasons (like why 12 password characters instead of 8).

Let me know. Love the project!

**Comment by josevalim** [comment]
Thanks for the discussion.

I agree we should standardized on one of e-mail or email, it doesn't matter which. @aaronrenner, wdyt?

Regarding sign in / sign out, I have read that "sign up" vs "sign in" is often confusing, especially for non-native speakers, so it is best to avoid the "sign *" conventions in general. That's why I picked register with log in and log out. So this particular aspect was thought out and I would prefer not to change it, if that makes any sense. :)

**Comment by zorn** [comment]
Thanks for the notes. I'm pretty ignorant of the non-native speakers issues around "sign in" so I'll have to research and consider that in my own work. 👍

**Comment by aaronrenner** [comment]
Thanks for bringing this up. I'd vote for `email` over `e-mail` as well and would absolutely merge a PR for it. :+1: 

As for `sign in`/`sign out` vs `log in`/`log out`, I think we'd still have the same verb issue that you have with `login`/`log in` except it would be `signin`/`sign in`. Also, when considering @josevalim's point about non-native speakers having issues with `sign in`/`sign out`/`sign up`, I'm leaning toward keeping the terminology as is.
