### ISSUE TITLE
Interested in Typespecs?

### ISSUE THREAD

**Issue by aj-foster** [aaronrenner/phx_gen_auth#51]
Hi there 👋 

Thank you for your work on this project. This is a fantastic resource for auth implementation as well as demonstrating Elixir and Phoenix in general.

Are you interested in adding type specifications to the functions created by this project? I realize not everyone uses specs, so totally understand if you'd prefer not to. 🙂 

If so, I'm happy to contribute towards this effort with your guidance.

**Comment by josevalim** [comment]
Hi @aj-foster! Given the goal is inclusion in Phoenix and Phoenix generators do not include typespecs, I would say we should not include typespecs here too. Thank you for reaching out tho!

**Comment by aaronrenner** [comment]
Thanks for reaching out @aj-foster! Although I personally use typespecs in my code, it would be inconsistent to have `mix phx.gen.auth` generate typespecs while `mix phx.gen.html` does not. Since this project will eventually be merged into phoenix, I definitely feel the need maintain consistency with the rest of the code phoenix generates. 

Thanks for bringing this up, though!
