### ISSUE TITLE
Simplify layout injection

### ISSUE THREAD

**Issue by josevalim** [aaronrenner/phx_gen_auth#8]
Suggestion: [this code](https://github.com/aaronrenner/phx_gen_auth/blob/master/lib/mix/tasks/phx.gen.auth.ex#L430) can probably just inject it after the opening `<body>` tag. It will be wrong but people will have to move it anyway. WDYT?

**Comment by aaronrenner** [comment]
I think that makes sense, especially since this code removes the LiveDashboard link. It would be cool if `_user_menu.html` could be nicely merged into the generated phoenix app's menu with some default CSS, but that could be a future improvement.

Thanks for suggesting this option. I'll get working on it. :heart:
